<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</div>

<script>
$(".menu_main .mega-menu-toggle #mega-toggle-block-1").click(function(){
$(this).parent().siblings(".mega-menu").addClass("active");
$('body').addClass('body_overflow');
$('.body_inner').addClass('active');
});

$("#mega-menu-wrap-max_mega_menu_2 .mega-menu-toggle #mega-toggle-block-1").click(function(){
$(this).parent().siblings(".mega-menu").addClass("active");
$('body').addClass('body_overflow');
$('.body_inner').addClass('active');
});

$(".body_overlay").click(function(){
$(this).siblings().find(".mega-menu.active").removeClass("active");
$('.body_inner').removeClass('active');	
$('body').removeClass('body_overflow');	
});
</script>
<script>
 if($("#mega-menu-max_mega_menu_2 li.mega-current-menu-item").length > 0)
{
var active_nav_text = $("#mega-menu-max_mega_menu_2 li.mega-current-menu-item").html()
$('.mobile_nav_category').html('<ul class="select_menu afclr"><li>' + active_nav_text + '</li></ul>');
}

</script>
<script>
$('html').find('.vanilla-category-nav-bh').addClass('afclr');
</script>
<script>
$('.select_menu > li > a.mega-menu-link').click(function(e) {
	event.preventDefault();
    $(this).siblings('.mega-sub-menu').toggleClass('active')
});
 	

</script>
<script>
	$ = jQuery;
    	 
    $(".s_bar").click(function(){
        $(this).toggleClass("active");
	})
	$(".s_form").click(function(){
        $(this).toggleClass("active");
			 
		 })
    $('body').click(function(){
	$('.s_bar').removeClass('active');
	$('.s_form').removeClass('active');
	})
	$('.s_bar').click(function(e){
	e.stopPropagation();
	})
		
	
	</script>
</body>
</html>
