<?php

/*
Template Name Posts: vanilla blog single
*/

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles single entries, but only exists for the sake of child theme forward compatibility.
include_once('functions.php');
get_header();

?>

<div class="site-inner">
<section class="row row-content">
<div class="col-lg-12 vanilla-single-content">
	<div id="primary" class="content-area">
	<main id="main" class="site-main" role="main">
		<?php
		// Start the loop.
		while ( have_posts() ) : the_post(); 
            $categories = get_the_category();
			// Include the single post content template.
		?>
		<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<header class="entry-header">
	    

	<?php
if(function_exists('like_counter_p')) { like_counter_p(''); }
?>	<?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
	</header><!-- .entry-header -->
 <div class="blog_sub_heading"><?php the_field('sub-heading'); ?></div>
	<?php the_content(); ?>
<div class="author_outer afclr">
    <div class = "quantum-author-section">
		<div class="quantum-author-image"><?php echo get_avatar( get_the_author_meta( 'ID' ), 42 ); ?> </div>
		<div class="quantum-author-name"><?php the_author_posts_link(); ?><span> in </span> 
		    <span class="quantum-home-cat"><a href=""><?php echo esc_html( $categories[0]->name); ?></a></span>
		</div>
		<div class="quantum-home-date"><?php echo human_time_diff( get_the_time('U'), current_time('timestamp') ) . ' ago'; ?></div>
		<div class ="quantum-home-read"><?php post_read_time(); ?></div>
	</div>
	<div class="singl_social_icon">
	    <a>Share this</a>
        <a href="https://www.facebook.com/vanillaforums"><i class="fa fa-facebook-square" aria-hidden="true"></i>Facebook</a>
        <a href="https://twitter.com/vanilla"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
        <a href="https://plus.google.com/114911737178548458245"><i class="fa fa-google-plus" aria-hidden="true"></i>Google</a>
        <a href="https://www.linkedin.com/company/1531758"><i class="fa fa-linkedin" aria-hidden="true"></i>LinkedIn
        </a>
	</div>
    </div>
    
	<div class="entry-content">
		<?php
		//	the_content();

			wp_link_pages( array(
				'before'      => '<div class="page-links afclr"><span class="page-links-title">' . __( 'Pages:', 'genesis-sample' ) . '</span>',
				'after'       => '</div>',
				'link_before' => '<span>',
				'link_after'  => '</span>',
				'pagelink'    => '<span class="screen-reader-text">' . __( 'Page', 'genesis-sample' ) . ' </span>%',
				'separator'   => '<span class="screen-reader-text">, </span>',
			) );
		?>
	</div><!-- .entry-content -->
	<?php 
	if ( is_singular( 'attachment' ) ) {
				// Parent post navigation.
				the_post_navigation( array(
					'prev_text' => _x( '<span class="meta-nav">Published in</span><span class="post-title">%title</span>', 'Parent post link', 'genesis-sample' ),
				) );
			} elseif ( is_singular( 'post' ) ) {
				// Previous/next post navigation.
				the_post_navigation( array(
				
					'next_text' => '<div class="afclr"><div class="next_content">' . __( 'Next Post', 'genesis-sample' ) . '</span> ' .
						'<span class="screen-reader-text">' . __( 'Next post:', 'genesis-sample' ) . '</span> ' .'</br>' .
						'<span class="post-title">%title</span></div>' . '<i class="fa fa-angle-right next_arrow" aria-hidden="true"></i></div>' ,
					'prev_text' => '<div class="afclr"><i class="fa fa-angle-left prev_arrow" aria-hidden="true"></i> <div class="prev_content">' .  __( 'Previous Post', 'genesis-sample' ) . '</span> ' .
						'<span class="screen-reader-text">' . __( 'Previous post:', 'genesis-sample' ) . '</span> ' . '</br>' .
						'<span class="post-title">%title</span></div></div>',
				) );
			}
		?>
</article><!-- #post-## -->
<?php 
			

			// End of the loop.
		endwhile;
		?>


<!-- comments............................ -->
<div id="vanilla-comments">
	
</div>
<script type="text/javascript">
var vanilla_forum_url = 'https://comments.vanillacommunity.com/'; // Required: the full http url & path to your vanilla forum
var vanilla_identifier = '9911'; // Required: your unique identifier for the content being commented on
var vanilla_url = '<?php the_permalink();  ?>'; // Current page's url
//var vanilla_category_id = '2'; // Embed comments in this category
(function() {
	var vanilla = document.createElement('script');
	vanilla.type = 'text/javascript';
	var timestamp = new Date().getTime();
	vanilla.src = vanilla_forum_url + '/js/embed.js';
	(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(vanilla);
})();
</script>
	</main><!-- .site-main -->


</div><!-- .content-area -->

</div>
</section>

<?php 
get_sidebar(); ?>

</div>

<div class="re_post">
<div class="site-inner">
<h3>Related Post</h3>
<?php dynamic_sidebar('sidebar-alt'); ?>
</div>
</div>
<?php get_footer(); ?>